import { useData } from '../context/DataContext';

const COLORS = [
  '#3B82F6', '#F43F5E', '#10B981', '#F59E0B', '#8B5CF6', '#14B8A6', '#64748B'
];

export const useAnalysis = () => {
  const { dashboardData } = useData();
  const hasData = !!dashboardData;
  const kpis = dashboardData?.kpis ?? {};
  
  const revenueTrend = dashboardData?.charts?.revenue_trend ?? [];
  const forecastTrend = dashboardData?.charts?.forecast ?? [];

  const combinedForecast = [
    ...revenueTrend.map((v, i) => ({
      month: v.month || `P${i + 1}`,
      revenue: v.revenue ?? v,
    })),
    ...forecastTrend.map((v, i) => ({
      month: v.month || `P${revenueTrend.length + i + 1}`,
      forecast: v.revenue ?? v.forecast ?? v,
    })),
  ];

  const expensesObj = dashboardData?.charts?.expense_breakdown ?? {};
  const totalExp = Object.values(expensesObj).reduce((sum, val) => sum + (val || 0), 0);
  const expenseData = Object.entries(expensesObj).map(([name, value], i) => ({
    name,
    value,
    pct: totalExp > 0 ? ((value / totalExp) * 100).toFixed(1) : 0,
    color: COLORS[i % COLORS.length]
  })).sort((a, b) => b.value - a.value);

  const riskLevel = dashboardData?.risk?.level ?? 'UNKNOWN';
  const riskFlags = dashboardData?.risk?.details?.risk_flags ?? [];
  
  const anomalyAlerts = riskFlags.map((flag, i) => ({
    id: i,
    title: 'Risk Flag Detected',
    detail: flag,
    severity: riskLevel === 'CRITICAL' || riskLevel === 'HIGH' ? 'critical' : 'warning',
    category: 'Risk Assessment',
    deviation: riskLevel
  }));

  const recommendations = (dashboardData?.insights?.recommendations ?? []).map((text, index) => {
    let priority = 'Low';
    let color = 'blue';
    if (text.toLowerCase().includes('critical') || text.toLowerCase().includes('immediate')) {
      priority = 'High'; color = 'red';
    } else if (text.toLowerCase().includes('consider') || text.toLowerCase().includes('monitor')) {
      priority = 'Medium'; color = 'amber';
    }
    return {
      id: index + 1,
      action: text,
      rationale: 'Generated by AI auditor analysis based on financial patterns.',
      priority,
      impact: 'Strategic',
      color
    };
  });

  const bData = [
    { company: 'TCS', profitMargin: 25.2, color: '#3B82F6' },
    { company: 'Infosys', profitMargin: 22.8, color: '#10B981' },
    { company: 'Wipro', profitMargin: 18.5, color: '#F59E0B' },
  ];
  if (kpis.profit_margin) {
    bData.unshift({ company: 'Your Company', profitMargin: parseFloat(kpis.profit_margin), color: '#8B5CF6' });
  }

  return {
    isReal: hasData,
    kpiCards: [],
    trendData: combinedForecast, // alias used by some
    forecastData: combinedForecast,
    expenseData,
    anomalyAlerts,
    benchmarkData: bData,
    recommendations,
    healthScore: { score: dashboardData?.health_score ?? 0, label: 'Financial Health', breakdown: [] },
    scenarioData: [
      { scenario: 'Current', profit: kpis.profit ?? 0 },
      { scenario: '+10% Revenue', profit: (kpis.profit ?? 0) * 1.15 },
      { scenario: '-10% Revenue', profit: (kpis.profit ?? 0) * 0.85 }
    ],
    risk: { risk_level: riskLevel, risk_flags: riskFlags },
    auditorExplanation: dashboardData?.insights?.summary ?? null,
  };
};
